/*
 * common.c
 *
 *  Created on: 2023Äê1ÔÂ9ÈÕ
 *      Author: wakoj
 */

#include <ff.h>

#define FF_ERROR_ITEM(e)		[e] = #e
const char* FF_ERRORS[20] = {
	FF_ERROR_ITEM(FR_OK),
	FF_ERROR_ITEM(FR_DISK_ERR),
	FF_ERROR_ITEM(FR_INT_ERR),
	FF_ERROR_ITEM(FR_NOT_READY),
	FF_ERROR_ITEM(FR_NO_FILE),
	FF_ERROR_ITEM(FR_NO_PATH),
	FF_ERROR_ITEM(FR_INVALID_NAME),
	FF_ERROR_ITEM(FR_DENIED),
	FF_ERROR_ITEM(FR_EXIST),
	FF_ERROR_ITEM(FR_INVALID_OBJECT),
	FF_ERROR_ITEM(FR_WRITE_PROTECTED),
	FF_ERROR_ITEM(FR_INVALID_DRIVE),
	FF_ERROR_ITEM(FR_NOT_ENABLED),
	FF_ERROR_ITEM(FR_NO_FILESYSTEM),
	FF_ERROR_ITEM(FR_MKFS_ABORTED),
	FF_ERROR_ITEM(FR_TIMEOUT),
	FF_ERROR_ITEM(FR_LOCKED),
	FF_ERROR_ITEM(FR_NOT_ENOUGH_CORE),
	FF_ERROR_ITEM(FR_TOO_MANY_OPEN_FILES),
	FF_ERROR_ITEM(FR_INVALID_PARAMETER),
};

